fix commands is None issue
Traceback (most recent call last):
  File "/usr/local/bin/vagga", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/vagga_docker/main.py", line 49, in main
    vagga.network_container = network.check_container(vagga, cli)
  File "/usr/local/lib/python3.7/site-packages/vagga_docker/network.py", line 14, in check_container
    ports = _find_all_exposed_ports(vagga)
  File "/usr/local/lib/python3.7/site-packages/vagga_docker/network.py", line 71, in _find_all_exposed_ports
    return frozenset(_exposed_ports(vagga.commands))
  File "/usr/local/lib/python3.7/site-packages/vagga_docker/network.py", line 75, in _exposed_ports
    for cmd in commands.values():
AttributeError: 'NoneType' object has no attribute 'values'